var listeThemes=[
	{"fichier":"quadrilateres","etiquette":"Quadrilatères","badges":[]},
	{"fichier":"calcul1","etiquette":"Calcul mental et logique","badges":[]},
	{"fichier":"fractions1","etiquette":"Fractions","badges":[]},
	{"fichier":"factorisation","etiquette":"Factorisation","badges":[]},
	{"fichier":"arithmetique1","etiquette":"Arithmétique 1","badges":[]},
	{"fichier":"systemes_lin","etiquette":"Systèmes","badges":[]},
	{"fichier":"droites","etiquette":"Droites","badges":[]},
	{"fichier":"domaines1","etiquette":"Domaines de déf°","badges":[]},
	{"fichier":"inegalites1","etiquette":"Inégalités","badges":[]},
	{"fichier":"trigo1","etiquette":"Trigo 1","badges":[]},
	{"fichier":"trigo2","etiquette":"Trigo 2","badges":[]},
	{"fichier":"derivees1","etiquette":"Dérivées 1","badges":[]},
	{"fichier":"derivees2","etiquette":"Dérivées 2","badges":[]},
	{"fichier":"complexes1","etiquette":"ℂ (forme alg)","badges":[]},
	{"fichier":"complexes2","etiquette":"ℂ (argument)","badges":[]},
	{"fichier":"equations","etiquette":"Équations","badges":[]},
	{"fichier":"recap","etiquette":"Récap","badges":[]},
	{"fichier":"complexes3","etiquette":"ℂ (module)","badges":[]},
	{"fichier":"complexes4","etiquette":"ℂ (géométrie)","badges":[]},
	{"fichier":"module_un","etiquette":"𝕌 et 𝕌<sub>n</sub>","badges":[]},
	{"fichier":"todo/rotations","etiquette":"Rotations","badges":[]},
	{"fichier":"implication","etiquette":"Implication","badges":[]},
	{"fichier":"predicats","etiquette":"Prédicats","badges":[]},
	{"fichier":"quantificateurs","etiquette":"Quantificateurs","badges":[]},
	{"fichier":"analyse1","etiquette":"Analyse","badges":[]},
	{"fichier":"applications1","etiquette":"Applications","badges":[]},
	{"fichier":"trigo3","etiquette":"Trigo 3","badges":[]},
	{"fichier":"trigo4","etiquette":"Trigo 4","badges":[]},
	{"fichier":"ev","etiquette":"Esp. vectoriels","badges":[]},
	{"fichier":"applications_lin","etiquette":"App. linéaires","badges":[]},
	{"fichier":"matrices","etiquette":"Matrices","badges":[]}
];